export const DELETE_TICKET = "DELETE_TICKET";
export const GET_ALL_TICKETS="GET_ALL_TICKETS";
export const SUCCESS="GET_ALL_TICKETS_SUCCESS";
export const ERROR="GET_ALL_TICKETS_ERROR";
export const TICKET_ADD_SUCCESS="TICKET_ADD_SUCCESS";