export const DELETE_TICKET = "DELETE_TICKET";
export const GET_ALL_TICKETS="GET_ALL_TICKETS";
export const GET_ALL_TICKETS_SUCCESS="GET_ALL_TICKETS_SUCCESS";
export const GET_ALL_TICKETS_ERROR="GET_ALL_TICKETS_ERROR";